// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/goolanger/swaggerize-auth/test/client/oauth"
	"github.com/goolanger/swaggerize-auth/test/client/scopes"
	"github.com/goolanger/swaggerize-auth/test/client/session"
)

// Default github com goolanger swaggerize auth HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new github com goolanger swaggerize auth HTTP client.
func NewHTTPClient(formats strfmt.Registry) *GithubComGoolangerSwaggerizeAuth {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new github com goolanger swaggerize auth HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *GithubComGoolangerSwaggerizeAuth {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new github com goolanger swaggerize auth client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *GithubComGoolangerSwaggerizeAuth {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(GithubComGoolangerSwaggerizeAuth)
	cli.Transport = transport
	cli.Oauth = oauth.New(transport, formats)
	cli.Scopes = scopes.New(transport, formats)
	cli.Session = session.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// GithubComGoolangerSwaggerizeAuth is a client for github com goolanger swaggerize auth
type GithubComGoolangerSwaggerizeAuth struct {
	Oauth oauth.ClientService

	Scopes scopes.ClientService

	Session session.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *GithubComGoolangerSwaggerizeAuth) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Oauth.SetTransport(transport)
	c.Scopes.SetTransport(transport)
	c.Session.SetTransport(transport)
}
