// Code generated by go-swagger; DO NOT EDIT.

package oauth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// ProviderInternalServerErrorCode is the HTTP code returned for type ProviderInternalServerError
const ProviderInternalServerErrorCode int = 500

/*ProviderInternalServerError internal server error

swagger:response providerInternalServerError
*/
type ProviderInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewProviderInternalServerError creates ProviderInternalServerError with default headers values
func NewProviderInternalServerError() *ProviderInternalServerError {

	return &ProviderInternalServerError{}
}

// WithPayload adds the payload to the provider internal server error response
func (o *ProviderInternalServerError) WithPayload(payload string) *ProviderInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the provider internal server error response
func (o *ProviderInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ProviderInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
