// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RecoveryHandlerFunc turns a function with the right signature into a recovery handler
type RecoveryHandlerFunc func(RecoveryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RecoveryHandlerFunc) Handle(params RecoveryParams) middleware.Responder {
	return fn(params)
}

// RecoveryHandler interface for that can handle valid recovery params
type RecoveryHandler interface {
	Handle(RecoveryParams) middleware.Responder
}

// NewRecovery creates a new http.Handler for the recovery operation
func NewRecovery(ctx *middleware.Context, handler RecoveryHandler) *Recovery {
	return &Recovery{Context: ctx, Handler: handler}
}

/*Recovery swagger:route GET /auth/session/recovery Session recovery

Recovery recovery API

*/
type Recovery struct {
	Context *middleware.Context
	Handler RecoveryHandler
}

func (o *Recovery) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRecoveryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
