// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// RecoverySubmitHandlerFunc turns a function with the right signature into a recovery submit handler
type RecoverySubmitHandlerFunc func(RecoverySubmitParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RecoverySubmitHandlerFunc) Handle(params RecoverySubmitParams) middleware.Responder {
	return fn(params)
}

// RecoverySubmitHandler interface for that can handle valid recovery submit params
type RecoverySubmitHandler interface {
	Handle(RecoverySubmitParams) middleware.Responder
}

// NewRecoverySubmit creates a new http.Handler for the recovery submit operation
func NewRecoverySubmit(ctx *middleware.Context, handler RecoverySubmitHandler) *RecoverySubmit {
	return &RecoverySubmit{Context: ctx, Handler: handler}
}

/*RecoverySubmit swagger:route POST /auth/session/recovery Session recoverySubmit

RecoverySubmit recovery submit API

*/
type RecoverySubmit struct {
	Context *middleware.Context
	Handler RecoverySubmitHandler
}

func (o *RecoverySubmit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRecoverySubmitParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
