// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RecoveryOKCode is the HTTP code returned for type RecoveryOK
const RecoveryOKCode int = 200

/*RecoveryOK OK

swagger:response recoveryOK
*/
type RecoveryOK struct {
}

// NewRecoveryOK creates RecoveryOK with default headers values
func NewRecoveryOK() *RecoveryOK {

	return &RecoveryOK{}
}

// WriteResponse to the client
func (o *RecoveryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// RecoveryInternalServerErrorCode is the HTTP code returned for type RecoveryInternalServerError
const RecoveryInternalServerErrorCode int = 500

/*RecoveryInternalServerError internal server error

swagger:response recoveryInternalServerError
*/
type RecoveryInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewRecoveryInternalServerError creates RecoveryInternalServerError with default headers values
func NewRecoveryInternalServerError() *RecoveryInternalServerError {

	return &RecoveryInternalServerError{}
}

// WithPayload adds the payload to the recovery internal server error response
func (o *RecoveryInternalServerError) WithPayload(payload string) *RecoveryInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the recovery internal server error response
func (o *RecoveryInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RecoveryInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
