// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// StateOKCode is the HTTP code returned for type StateOK
const StateOKCode int = 200

/*StateOK OK

swagger:response stateOK
*/
type StateOK struct {
}

// NewStateOK creates StateOK with default headers values
func NewStateOK() *StateOK {

	return &StateOK{}
}

// WriteResponse to the client
func (o *StateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// StateInternalServerErrorCode is the HTTP code returned for type StateInternalServerError
const StateInternalServerErrorCode int = 500

/*StateInternalServerError internal server error

swagger:response stateInternalServerError
*/
type StateInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewStateInternalServerError creates StateInternalServerError with default headers values
func NewStateInternalServerError() *StateInternalServerError {

	return &StateInternalServerError{}
}

// WithPayload adds the payload to the state internal server error response
func (o *StateInternalServerError) WithPayload(payload string) *StateInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the state internal server error response
func (o *StateInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StateInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
