// Code generated by go-swagger; DO NOT EDIT.

// Package server University Staff
//
//  This website will stand for the administration and information digital support for any university.
//  Terms Of Service:
//    https://ulikeit.io/terms/
//  Schemes:
//    http
//    https
//  Host: localhost:20443
//  BasePath: /
//  Version: 0.1.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: Amaury<amauryuh@gmail.com> https://amaurydiaz.github.io
//
//  Consumes:
//    - application/x-www-form-urlencoded
//
//  Produces:
//    - text/html
//    - application/json
//
// swagger:meta
package server
