// Code generated by go-swagger; DO NOT EDIT.

package server

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This website will stand for the administration and information digital support for any university.",
    "title": "University Staff",
    "termsOfService": "https://ulikeit.io/terms/",
    "contact": {
      "name": "Amaury",
      "url": "https://amaurydiaz.github.io",
      "email": "amauryuh@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.1.0"
  },
  "host": "localhost:20443",
  "paths": {
    "/api/oauth/authorize": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Oauth"
        ],
        "operationId": "Authorize",
        "parameters": [
          {
            "type": "string",
            "name": "redirect_uri",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "client_id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "state",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "scope",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "Oauth"
        ],
        "operationId": "AuthorizeSubmit",
        "parameters": [
          {
            "enum": [
              "code",
              "token"
            ],
            "type": "string",
            "name": "response_type",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "redirect_uri",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "client_id",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "state",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "scope",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "username",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "operation success"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/oauth/providers/{provider}": {
      "get": {
        "security": [],
        "tags": [
          "Oauth"
        ],
        "operationId": "Provider",
        "parameters": [
          {
            "type": "string",
            "name": "provider",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "code",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "state",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/oauth/token": {
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "Oauth"
        ],
        "operationId": "Token",
        "parameters": [
          {
            "enum": [
              "password",
              "authorization_code",
              "client_credentials",
              "refresh_token"
            ],
            "type": "string",
            "name": "grant_type",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "client_id",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "client_secret",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "scope",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "redirect_uri",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "code",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "username",
            "in": "formData"
          },
          {
            "type": "string",
            "format": "password",
            "name": "password",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "refresh_token",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "operation success",
            "schema": {
              "type": "object",
              "properties": {
                "access_token": {
                  "type": "string"
                },
                "expires_in": {
                  "type": "integer",
                  "format": "int32"
                },
                "refresh_token": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "token_type": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/scope/info": {
      "get": {
        "security": [
          {
            "scoped": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Scopes"
        ],
        "operationId": "Info",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "verified_email": {
                  "type": "boolean"
                }
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/recovery": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "Recovery",
        "parameters": [
          {
            "type": "string",
            "name": "token",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "RecoverySubmit",
        "parameters": [
          {
            "type": "string",
            "format": "password",
            "name": "password",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "token",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/register": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "Register",
        "parameters": [
          {
            "type": "string",
            "name": "login-url",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "RegisterSubmit",
        "parameters": [
          {
            "type": "string",
            "name": "email",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "409": {
            "description": "conflict"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/register/activate": {
      "get": {
        "security": [],
        "tags": [
          "Session"
        ],
        "operationId": "RegisterActivate",
        "parameters": [
          {
            "type": "string",
            "name": "token",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/state": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "State",
        "parameters": [
          {
            "enum": [
              "activation",
              "recovery"
            ],
            "type": "string",
            "name": "action",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "StateSubmit",
        "parameters": [
          {
            "type": "string",
            "name": "email",
            "in": "formData",
            "required": true
          },
          {
            "enum": [
              "activation",
              "recovery"
            ],
            "type": "string",
            "name": "action",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/state/message": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "StateMessage",
        "parameters": [
          {
            "enum": [
              "activation",
              "recovery",
              "activated",
              "recovered"
            ],
            "type": "string",
            "name": "action",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Claims": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "scopes": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    },
    "scoped": {
      "type": "apiKey",
      "name": "access_token",
      "in": "query"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "description": "Oauth 2.0 authorization protocol endpoints.",
      "name": "Oauth"
    },
    {
      "description": "Session actions for users.",
      "name": "Session"
    },
    {
      "description": "Oauth scopes",
      "name": "Scopes"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This website will stand for the administration and information digital support for any university.",
    "title": "University Staff",
    "termsOfService": "https://ulikeit.io/terms/",
    "contact": {
      "name": "Amaury",
      "url": "https://amaurydiaz.github.io",
      "email": "amauryuh@gmail.com"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "0.1.0"
  },
  "host": "localhost:20443",
  "paths": {
    "/api/oauth/authorize": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Oauth"
        ],
        "operationId": "Authorize",
        "parameters": [
          {
            "type": "string",
            "name": "redirect_uri",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "client_id",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "state",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "scope",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "Oauth"
        ],
        "operationId": "AuthorizeSubmit",
        "parameters": [
          {
            "enum": [
              "code",
              "token"
            ],
            "type": "string",
            "name": "response_type",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "redirect_uri",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "client_id",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "state",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "scope",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "username",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "operation success"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/oauth/providers/{provider}": {
      "get": {
        "security": [],
        "tags": [
          "Oauth"
        ],
        "operationId": "Provider",
        "parameters": [
          {
            "type": "string",
            "name": "provider",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "name": "code",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "state",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/oauth/token": {
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "tags": [
          "Oauth"
        ],
        "operationId": "Token",
        "parameters": [
          {
            "enum": [
              "password",
              "authorization_code",
              "client_credentials",
              "refresh_token"
            ],
            "type": "string",
            "name": "grant_type",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "client_id",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "client_secret",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "scope",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "redirect_uri",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "code",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "username",
            "in": "formData"
          },
          {
            "type": "string",
            "format": "password",
            "name": "password",
            "in": "formData"
          },
          {
            "type": "string",
            "name": "refresh_token",
            "in": "formData"
          }
        ],
        "responses": {
          "200": {
            "description": "operation success",
            "schema": {
              "type": "object",
              "properties": {
                "access_token": {
                  "type": "string"
                },
                "expires_in": {
                  "type": "integer",
                  "format": "int32"
                },
                "refresh_token": {
                  "type": "string"
                },
                "scope": {
                  "type": "string"
                },
                "token_type": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/scope/info": {
      "get": {
        "security": [
          {
            "scoped": []
          }
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Scopes"
        ],
        "operationId": "Info",
        "responses": {
          "200": {
            "description": "ok",
            "schema": {
              "type": "object",
              "properties": {
                "email": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                },
                "verified_email": {
                  "type": "boolean"
                }
              }
            }
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/recovery": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "Recovery",
        "parameters": [
          {
            "type": "string",
            "name": "token",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "RecoverySubmit",
        "parameters": [
          {
            "type": "string",
            "format": "password",
            "name": "password",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "token",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/register": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "Register",
        "parameters": [
          {
            "type": "string",
            "name": "login-url",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "RegisterSubmit",
        "parameters": [
          {
            "type": "string",
            "name": "email",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "name": "password",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "409": {
            "description": "conflict"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/register/activate": {
      "get": {
        "security": [],
        "tags": [
          "Session"
        ],
        "operationId": "RegisterActivate",
        "parameters": [
          {
            "type": "string",
            "name": "token",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/state": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "State",
        "parameters": [
          {
            "enum": [
              "activation",
              "recovery"
            ],
            "type": "string",
            "name": "action",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "security": [],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "StateSubmit",
        "parameters": [
          {
            "type": "string",
            "name": "email",
            "in": "formData",
            "required": true
          },
          {
            "enum": [
              "activation",
              "recovery"
            ],
            "type": "string",
            "name": "action",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/api/session/state/message": {
      "get": {
        "security": [],
        "produces": [
          "text/html"
        ],
        "tags": [
          "Session"
        ],
        "operationId": "StateMessage",
        "parameters": [
          {
            "enum": [
              "activation",
              "recovery",
              "activated",
              "recovered"
            ],
            "type": "string",
            "name": "action",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "500": {
            "description": "internal server error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Claims": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "scopes": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    },
    "scoped": {
      "type": "apiKey",
      "name": "access_token",
      "in": "query"
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "description": "Oauth 2.0 authorization protocol endpoints.",
      "name": "Oauth"
    },
    {
      "description": "Session actions for users.",
      "name": "Session"
    },
    {
      "description": "Oauth scopes",
      "name": "Scopes"
    }
  ]
}`))
}
