// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RecoverySubmitReader is a Reader for the RecoverySubmit structure.
type RecoverySubmitReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RecoverySubmitReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRecoverySubmitOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewRecoverySubmitInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRecoverySubmitOK creates a RecoverySubmitOK with default headers values
func NewRecoverySubmitOK() *RecoverySubmitOK {
	return &RecoverySubmitOK{}
}

/*RecoverySubmitOK handles this case with default header values.

OK
*/
type RecoverySubmitOK struct {
}

func (o *RecoverySubmitOK) Error() string {
	return fmt.Sprintf("[POST /auth/session/recovery][%d] recoverySubmitOK ", 200)
}

func (o *RecoverySubmitOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRecoverySubmitInternalServerError creates a RecoverySubmitInternalServerError with default headers values
func NewRecoverySubmitInternalServerError() *RecoverySubmitInternalServerError {
	return &RecoverySubmitInternalServerError{}
}

/*RecoverySubmitInternalServerError handles this case with default header values.

internal server error
*/
type RecoverySubmitInternalServerError struct {
	Payload string
}

func (o *RecoverySubmitInternalServerError) Error() string {
	return fmt.Sprintf("[POST /auth/session/recovery][%d] recoverySubmitInternalServerError  %+v", 500, o.Payload)
}

func (o *RecoverySubmitInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *RecoverySubmitInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
