// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRecoverySubmitParams creates a new RecoverySubmitParams object
// with the default values initialized.
func NewRecoverySubmitParams() *RecoverySubmitParams {
	var ()
	return &RecoverySubmitParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRecoverySubmitParamsWithTimeout creates a new RecoverySubmitParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRecoverySubmitParamsWithTimeout(timeout time.Duration) *RecoverySubmitParams {
	var ()
	return &RecoverySubmitParams{

		timeout: timeout,
	}
}

// NewRecoverySubmitParamsWithContext creates a new RecoverySubmitParams object
// with the default values initialized, and the ability to set a context for a request
func NewRecoverySubmitParamsWithContext(ctx context.Context) *RecoverySubmitParams {
	var ()
	return &RecoverySubmitParams{

		Context: ctx,
	}
}

// NewRecoverySubmitParamsWithHTTPClient creates a new RecoverySubmitParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRecoverySubmitParamsWithHTTPClient(client *http.Client) *RecoverySubmitParams {
	var ()
	return &RecoverySubmitParams{
		HTTPClient: client,
	}
}

/*RecoverySubmitParams contains all the parameters to send to the API endpoint
for the recovery submit operation typically these are written to a http.Request
*/
type RecoverySubmitParams struct {

	/*Password*/
	Password strfmt.Password
	/*Token*/
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the recovery submit params
func (o *RecoverySubmitParams) WithTimeout(timeout time.Duration) *RecoverySubmitParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the recovery submit params
func (o *RecoverySubmitParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the recovery submit params
func (o *RecoverySubmitParams) WithContext(ctx context.Context) *RecoverySubmitParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the recovery submit params
func (o *RecoverySubmitParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the recovery submit params
func (o *RecoverySubmitParams) WithHTTPClient(client *http.Client) *RecoverySubmitParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the recovery submit params
func (o *RecoverySubmitParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPassword adds the password to the recovery submit params
func (o *RecoverySubmitParams) WithPassword(password strfmt.Password) *RecoverySubmitParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the recovery submit params
func (o *RecoverySubmitParams) SetPassword(password strfmt.Password) {
	o.Password = password
}

// WithToken adds the token to the recovery submit params
func (o *RecoverySubmitParams) WithToken(token string) *RecoverySubmitParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the recovery submit params
func (o *RecoverySubmitParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *RecoverySubmitParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// form param password
	frPassword := o.Password
	fPassword := frPassword.String()
	if fPassword != "" {
		if err := r.SetFormParam("password", fPassword); err != nil {
			return err
		}
	}

	// query param token
	qrToken := o.Token
	qToken := qrToken
	if qToken != "" {
		if err := r.SetQueryParam("token", qToken); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
