// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RegisterActivateReader is a Reader for the RegisterActivate structure.
type RegisterActivateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RegisterActivateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRegisterActivateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewRegisterActivateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRegisterActivateOK creates a RegisterActivateOK with default headers values
func NewRegisterActivateOK() *RegisterActivateOK {
	return &RegisterActivateOK{}
}

/*RegisterActivateOK handles this case with default header values.

OK
*/
type RegisterActivateOK struct {
}

func (o *RegisterActivateOK) Error() string {
	return fmt.Sprintf("[GET /api/session/register/activate][%d] registerActivateOK ", 200)
}

func (o *RegisterActivateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRegisterActivateInternalServerError creates a RegisterActivateInternalServerError with default headers values
func NewRegisterActivateInternalServerError() *RegisterActivateInternalServerError {
	return &RegisterActivateInternalServerError{}
}

/*RegisterActivateInternalServerError handles this case with default header values.

internal server error
*/
type RegisterActivateInternalServerError struct {
	Payload string
}

func (o *RegisterActivateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/session/register/activate][%d] registerActivateInternalServerError  %+v", 500, o.Payload)
}

func (o *RegisterActivateInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *RegisterActivateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
