// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// StateMessageReader is a Reader for the StateMessage structure.
type StateMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StateMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStateMessageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewStateMessageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStateMessageOK creates a StateMessageOK with default headers values
func NewStateMessageOK() *StateMessageOK {
	return &StateMessageOK{}
}

/*StateMessageOK handles this case with default header values.

OK
*/
type StateMessageOK struct {
}

func (o *StateMessageOK) Error() string {
	return fmt.Sprintf("[GET /api/session/state/message][%d] stateMessageOK ", 200)
}

func (o *StateMessageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewStateMessageInternalServerError creates a StateMessageInternalServerError with default headers values
func NewStateMessageInternalServerError() *StateMessageInternalServerError {
	return &StateMessageInternalServerError{}
}

/*StateMessageInternalServerError handles this case with default header values.

internal server error
*/
type StateMessageInternalServerError struct {
	Payload string
}

func (o *StateMessageInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/session/state/message][%d] stateMessageInternalServerError  %+v", 500, o.Payload)
}

func (o *StateMessageInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *StateMessageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
