// Code generated by go-swagger; DO NOT EDIT.

package session

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStateMessageParams creates a new StateMessageParams object
// with the default values initialized.
func NewStateMessageParams() *StateMessageParams {
	var ()
	return &StateMessageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStateMessageParamsWithTimeout creates a new StateMessageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStateMessageParamsWithTimeout(timeout time.Duration) *StateMessageParams {
	var ()
	return &StateMessageParams{

		timeout: timeout,
	}
}

// NewStateMessageParamsWithContext creates a new StateMessageParams object
// with the default values initialized, and the ability to set a context for a request
func NewStateMessageParamsWithContext(ctx context.Context) *StateMessageParams {
	var ()
	return &StateMessageParams{

		Context: ctx,
	}
}

// NewStateMessageParamsWithHTTPClient creates a new StateMessageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStateMessageParamsWithHTTPClient(client *http.Client) *StateMessageParams {
	var ()
	return &StateMessageParams{
		HTTPClient: client,
	}
}

/*StateMessageParams contains all the parameters to send to the API endpoint
for the state message operation typically these are written to a http.Request
*/
type StateMessageParams struct {

	/*Action*/
	Action string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the state message params
func (o *StateMessageParams) WithTimeout(timeout time.Duration) *StateMessageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the state message params
func (o *StateMessageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the state message params
func (o *StateMessageParams) WithContext(ctx context.Context) *StateMessageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the state message params
func (o *StateMessageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the state message params
func (o *StateMessageParams) WithHTTPClient(client *http.Client) *StateMessageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the state message params
func (o *StateMessageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAction adds the action to the state message params
func (o *StateMessageParams) WithAction(action string) *StateMessageParams {
	o.SetAction(action)
	return o
}

// SetAction adds the action to the state message params
func (o *StateMessageParams) SetAction(action string) {
	o.Action = action
}

// WriteToRequest writes these params to a swagger request
func (o *StateMessageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param action
	qrAction := o.Action
	qAction := qrAction
	if qAction != "" {
		if err := r.SetQueryParam("action", qAction); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
