// Code generated by go-swagger; DO NOT EDIT.

package oauth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ProviderReader is a Reader for the Provider structure.
type ProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 500:
		result := NewProviderInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewProviderInternalServerError creates a ProviderInternalServerError with default headers values
func NewProviderInternalServerError() *ProviderInternalServerError {
	return &ProviderInternalServerError{}
}

/*ProviderInternalServerError handles this case with default header values.

internal server error
*/
type ProviderInternalServerError struct {
	Payload string
}

func (o *ProviderInternalServerError) Error() string {
	return fmt.Sprintf("[GET /auth/oauth/providers/{provider}][%d] providerInternalServerError  %+v", 500, o.Payload)
}

func (o *ProviderInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *ProviderInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
